### ISSUE TITLE
BUG: Failed to work on Artik710

### ISSUE THREAD

**Issue by andrewjaykeller** [craig-mulligan/artik-gpio-python#1]
Problem:

Using GPIO results in `bash: echo: write error: Device or resource busy`

I tried to run this program on my Artik 710 and failed with:

```bash
Systemd init system enabled.
 main  systemd 215 running in system mode. (+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR)
 main  Detected virtualization 'other'.
 main  Detected architecture 'arm64'.
 main  Set hostname to <0176368>.
 main  Traceback (most recent call last):
 main    File "main.py", line 9, in <module>
 main      LED = GPIO(pinNum, "out")
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 43, in __init__
 main      self._open(pin, direction)
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 70, in _open
 main      raise GPIOError(e.errno, "Exporting GPIO: " + e.strerror)
 main  periphery.gpio.GPIOError: [Errno 16] Exporting GPIO: Deviceor resource busy
 main  Traceback (most recent call last):
 main    File "main.py", line 9, in <module>
 main      LED = GPIO(pinNum, "out")
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 43, in __init__
 main      self._open(pin, direction)
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 70, in _open
 main      raise GPIOError(e.errno, "Exporting GPIO: " + e.strerror)
 main  periphery.gpio.GPIOError: [Errno 16] Exporting GPIO: Deviceor resource busy
 main  Traceback (most recent call last):
 main    File "main.py", line 9, in <module>
 main      LED = GPIO(pinNum, "out")
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 43, in __init__
 main      self._open(pin, direction)
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 70, in _open
 main      raise GPIOError(e.errno, "Exporting GPIO: " + e.strerror)
 main  periphery.gpio.GPIOError: [Errno 16] Exporting GPIO: Deviceor resource busy
 main  Traceback (most recent call last):
 main    File "main.py", line 9, in <module>
 main      LED = GPIO(pinNum, "out")
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 43, in __init__
 main      self._open(pin, direction)
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 70, in _open
 main      raise GPIOError(e.errno, "Exporting GPIO: " + e.strerror)
 main  periphery.gpio.GPIOError: [Errno 16] Exporting GPIO: Deviceor resource busy
 main  Traceback (most recent call last):
 main    File "main.py", line 9, in <module>
 main      LED = GPIO(pinNum, "out")
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 43, in __init__
 main      self._open(pin, direction)
 main    File "/usr/local/lib/python2.7/site-packages/periphery/gpio.py", line 70, in _open
 main      raise GPIOError(e.errno, "Exporting GPIO: " + e.strerror)
 main  periphery.gpio.GPIOError: [Errno 16] Exporting GPIO: Deviceor resource busy
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cilv)

**Comment by andrewjaykeller** [comment]
Any ideas or help is greatly appreciated!
